### ISSUE TITLE
centos, start works but not others

### ISSUE THREAD

**Issue by bloodyKnuckles** [substack/psy#10] opened 2015-12-04 16:27 UTC
Using centos on digital ocean. `psy start -n NAME -- node index.js` seems to work, but no other `psy` commands work as expected. Not able to `ls`, not able to `stop`, and others.

**Comment by yoshuawuyts** [comment] 2015-12-05 12:13
Hey there, thanks for reporting this. I just tried this on `node@5` with a fresh install of `psy` on Debian and it all works fine. You might want to dig a little deeper into what is going on; check if there's perhaps errors not being caught. 

I'm going to close this because I can't reproduce, will reopen if / when more details arise. Thanks again!

**Closed by yoshuawuyts** 2015-12-05 12:13 UTC

**Comment by bloodyKnuckles** [comment] 2015-12-05 18:06
I've read CentOS is based on RHEL, not Debian. Has anyone been able to get other `psy` commands to work on CentOS or RHEL?

**Comment by yoshuawuyts** [comment] 2015-12-06 01:22
Ohey, I misread your issue sorry about that though. Though unless you can provide more details / a repro there's no point in leaving this issue open.

**Comment by bloodyKnuckles** [comment] 2015-12-06 19:32
I tried debugging today but got nowhere. I'm getting no errors. I'm using a CentOS 7.1 x64 vps. 

`psy start -n myapp -- node index.js`

...seems to work fine. I get nothing on the command line when running any `psy` commands including `start` but the `node index.js` does fire up and keep running.

`psy ls` does nothing, just returns to command line.
`psy list` hangs up, no error reported.
`psy stop myapp` does nothing, returns to command line, app still running.

**Comment by aredridel** [comment] 2015-12-07 01:50
SELinux?
